version: '3.4'

  
services:
  eventsourcingcourse:
    image: ${DOCKER_REGISTRY-}eventsourcingcourse
    build:
      context: .
      dockerfile: EventSourcingCourse/Dockerfile
    networks:
      - cqrs-network
  eventstoredb:
    image: eventstore/eventstore
    hostname: eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - cqrs-network
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

networks:
  cqrs-network:

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: